In [1]:
import numpy as np

In [ ]:
#1 What is a Python library? Why do we use Python libraries?

'''
Python library is a collection of pre-compiled functions which can be used later in a program for some specific purpose.
It makes programming simpler for the programmer. 
Most of the Python libraries are written in C programming language. 
'''

In [ ]:
#2 What is the difference between Numpy array and List?

'''
Numpy array can store data of same data type whereas List stores data of different types. 
Numpy arrays are optimized for numerical / mathematical operations whereas List is used for general purpose data structure. 
'''

In [13]:
#3 Find the shape, size and dimension of the following array?

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print("The dimension of array is",arr.ndim)
print("The size of array is",arr.size)
print("The shape of array is",arr.shape)

The dimension of array is 2
The size of array is 12
The shape of array is (3, 4)


In [4]:
#4 Write python code to access the first row of the following array?

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr[0])

[1 2 3 4]


In [7]:
#5 How do you access the element at the third row and fourth column from the given numpy array?

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr[2][3]

12

In [22]:
#7 How can you generate a random 3x3 matrix with values between 0 and 1?

arr=np.random.random((3,3))
arr

array([[0.74990409, 0.90503008, 0.85075466],
       [0.69635751, 0.94031569, 0.06901817],
       [0.8320791 , 0.02132894, 0.15096967]])

In [ ]:
#8 Describe the difference between np.random.rand and np.random.randn?

'''
np.random.rand is to generate sample for Uniform distribution
np.random.randn is to generate sample for Normal distribution
'''

arr1=np.random.rand(10)
print("Uniform distribution",arr1)

arr2=np.random.randn(10)
print("Normal distribution",arr2)

Uniform distribution [0.95653375 0.58302511 0.31622781 0.16350001 0.3862356  0.23999802
 0.68296812 0.61799662 0.83428652 0.08273926]
Normal distribution [-0.29881025  0.64854277 -0.90290281  1.03457153 -1.14676378  1.45737274
  0.15712981  0.24128202  0.51442588 -1.48161493]


In [31]:
#9 Write code to increase the dimension of the following array?

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1 = np.expand_dims(arr,axis=0)
arr1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [14]:
#10 How to transpose the following array in NumPy?

arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr.T


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [12]:
#11 Consider the following matrix:

matrixA = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
matrixB = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]

arr1 = np.array(matrixA)
arr2 = np.array(matrixB)

#1 Index wise multiplication

print("Index wise multiplication")
print(arr1 * arr2)

#2 Matrix multiplication

'''
Matrix multiplication (arr1 @ arr2) for above matrices cannot be performed as the number of columns of Matrix A is 
not equal to number of rows of Matrix B
'''

#3 Add both the matricK

print("Add both Matrices")
print(arr1 + arr2)


#4 Subtract matrix B from A

print(arr1-arr2)


#5 Divide Matrix B by A

arr2/arr1


Index wise multiplication
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Add both Matrices
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
#14 What does the np.reshape function do, and how is it used?

'''
Reshape function is used to change the shape of array without changing data
'''

arr=np.array([[1,2,3],[4,5,6]])
np.reshape(arr,(1,6))

array([[1, 2, 3, 4, 5, 6]])

In [33]:
#15 What is broadcasting in Numpy?

'''
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. 
Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. 
'''

# Example

arr1=np.array([1,2,3])
arr2=np.array([1])
arr1+arr2

array([2, 3, 4])